# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 549))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("QPushButton{\n"
"background-color:gray;\n"
"border-radius: 40%;\n"
"color:white;\n"
"}\n"
"QFrame#frame_5{\n"
"background-color:blue;\n"
"}\n"
"QPushButton#save{\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setMinimumSize(QtCore.QSize(420, 674))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.level_label = QtWidgets.QLabel(self.frame_2)
        self.level_label.setGeometry(QtCore.QRect(70, 230, 100, 30))
        self.level_label.setMinimumSize(QtCore.QSize(100, 30))
        self.level_label.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.level_label.setFont(font)
        self.level_label.setAlignment(QtCore.Qt.AlignCenter)
        self.level_label.setObjectName("level_label")
        self.levelComboBox = QtWidgets.QComboBox(self.frame_2)
        self.levelComboBox.setGeometry(QtCore.QRect(280, 240, 100, 30))
        self.levelComboBox.setMinimumSize(QtCore.QSize(100, 30))
        self.levelComboBox.setMaximumSize(QtCore.QSize(100, 30))
        self.levelComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.levelComboBox.setObjectName("levelComboBox")
        self.levelComboBox.addItem("")
        self.levelComboBox.addItem("")
        self.levelComboBox.addItem("")
        self.startButton = QtWidgets.QToolButton(self.frame_2)
        self.startButton.setGeometry(QtCore.QRect(260, 320, 100, 50))
        self.startButton.setMinimumSize(QtCore.QSize(100, 50))
        self.startButton.setMaximumSize(QtCore.QSize(100, 50))
        self.startButton.setObjectName("startButton")
        self.loadButton = QtWidgets.QToolButton(self.frame_2)
        self.loadButton.setGeometry(QtCore.QRect(290, 400, 100, 50))
        self.loadButton.setMinimumSize(QtCore.QSize(100, 50))
        self.loadButton.setMaximumSize(QtCore.QSize(100, 50))
        self.loadButton.setObjectName("loadButton")
        self.gridLayout_8.addWidget(self.frame_2, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.tab_4)
        self.frame_5.setMinimumSize(QtCore.QSize(760, 600))
        self.frame_5.setMaximumSize(QtCore.QSize(760, 600))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pb50 = QtWidgets.QPushButton(self.frame_5)
        self.pb50.setGeometry(QtCore.QRect(10, 10, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb50.sizePolicy().hasHeightForWidth())
        self.pb50.setSizePolicy(sizePolicy)
        self.pb50.setMinimumSize(QtCore.QSize(80, 80))
        self.pb50.setMaximumSize(QtCore.QSize(80, 80))
        self.pb50.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb50.setText("")
        self.pb50.setCheckable(True)
        self.pb50.setObjectName("pb50")
        self.pb51 = QtWidgets.QPushButton(self.frame_5)
        self.pb51.setGeometry(QtCore.QRect(110, 10, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb51.sizePolicy().hasHeightForWidth())
        self.pb51.setSizePolicy(sizePolicy)
        self.pb51.setMinimumSize(QtCore.QSize(80, 80))
        self.pb51.setMaximumSize(QtCore.QSize(80, 80))
        self.pb51.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb51.setText("")
        self.pb51.setObjectName("pb51")
        self.pb52 = QtWidgets.QPushButton(self.frame_5)
        self.pb52.setGeometry(QtCore.QRect(220, 10, 80, 80))
        self.pb52.setMinimumSize(QtCore.QSize(80, 80))
        self.pb52.setMaximumSize(QtCore.QSize(80, 80))
        self.pb52.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb52.setText("")
        self.pb52.setObjectName("pb52")
        self.pb53 = QtWidgets.QPushButton(self.frame_5)
        self.pb53.setGeometry(QtCore.QRect(330, 10, 80, 80))
        self.pb53.setMinimumSize(QtCore.QSize(80, 80))
        self.pb53.setMaximumSize(QtCore.QSize(80, 80))
        self.pb53.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb53.setText("")
        self.pb53.setObjectName("pb53")
        self.pb54 = QtWidgets.QPushButton(self.frame_5)
        self.pb54.setGeometry(QtCore.QRect(440, 10, 80, 80))
        self.pb54.setMinimumSize(QtCore.QSize(80, 80))
        self.pb54.setMaximumSize(QtCore.QSize(80, 80))
        self.pb54.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb54.setText("")
        self.pb54.setObjectName("pb54")
        self.pb55 = QtWidgets.QPushButton(self.frame_5)
        self.pb55.setGeometry(QtCore.QRect(550, 10, 80, 80))
        self.pb55.setMinimumSize(QtCore.QSize(80, 80))
        self.pb55.setMaximumSize(QtCore.QSize(80, 80))
        self.pb55.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb55.setText("")
        self.pb55.setObjectName("pb55")
        self.pb56 = QtWidgets.QPushButton(self.frame_5)
        self.pb56.setGeometry(QtCore.QRect(650, 10, 80, 80))
        self.pb56.setMinimumSize(QtCore.QSize(80, 80))
        self.pb56.setMaximumSize(QtCore.QSize(80, 80))
        self.pb56.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb56.setText("")
        self.pb56.setObjectName("pb56")
        self.pb40 = QtWidgets.QPushButton(self.frame_5)
        self.pb40.setGeometry(QtCore.QRect(10, 100, 80, 80))
        self.pb40.setMinimumSize(QtCore.QSize(80, 80))
        self.pb40.setMaximumSize(QtCore.QSize(80, 80))
        self.pb40.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb40.setText("")
        self.pb40.setObjectName("pb40")
        self.pb41 = QtWidgets.QPushButton(self.frame_5)
        self.pb41.setGeometry(QtCore.QRect(110, 100, 80, 80))
        self.pb41.setMinimumSize(QtCore.QSize(80, 80))
        self.pb41.setMaximumSize(QtCore.QSize(80, 80))
        self.pb41.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb41.setText("")
        self.pb41.setObjectName("pb41")
        self.pb42 = QtWidgets.QPushButton(self.frame_5)
        self.pb42.setGeometry(QtCore.QRect(220, 100, 80, 80))
        self.pb42.setMinimumSize(QtCore.QSize(80, 80))
        self.pb42.setMaximumSize(QtCore.QSize(80, 80))
        self.pb42.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb42.setText("")
        self.pb42.setObjectName("pb42")
        self.pb43 = QtWidgets.QPushButton(self.frame_5)
        self.pb43.setGeometry(QtCore.QRect(330, 100, 80, 80))
        self.pb43.setMinimumSize(QtCore.QSize(80, 80))
        self.pb43.setMaximumSize(QtCore.QSize(80, 80))
        self.pb43.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb43.setText("")
        self.pb43.setObjectName("pb43")
        self.pb44 = QtWidgets.QPushButton(self.frame_5)
        self.pb44.setGeometry(QtCore.QRect(440, 100, 80, 80))
        self.pb44.setMinimumSize(QtCore.QSize(80, 80))
        self.pb44.setMaximumSize(QtCore.QSize(80, 80))
        self.pb44.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb44.setText("")
        self.pb44.setObjectName("pb44")
        self.pb45 = QtWidgets.QPushButton(self.frame_5)
        self.pb45.setGeometry(QtCore.QRect(550, 100, 80, 80))
        self.pb45.setMinimumSize(QtCore.QSize(80, 80))
        self.pb45.setMaximumSize(QtCore.QSize(80, 80))
        self.pb45.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb45.setText("")
        self.pb45.setObjectName("pb45")
        self.pb46 = QtWidgets.QPushButton(self.frame_5)
        self.pb46.setGeometry(QtCore.QRect(650, 100, 80, 80))
        self.pb46.setMinimumSize(QtCore.QSize(80, 80))
        self.pb46.setMaximumSize(QtCore.QSize(80, 80))
        self.pb46.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb46.setText("")
        self.pb46.setObjectName("pb46")
        self.pb30 = QtWidgets.QPushButton(self.frame_5)
        self.pb30.setGeometry(QtCore.QRect(10, 190, 80, 80))
        self.pb30.setMinimumSize(QtCore.QSize(80, 80))
        self.pb30.setMaximumSize(QtCore.QSize(80, 80))
        self.pb30.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb30.setText("")
        self.pb30.setObjectName("pb30")
        self.pb31 = QtWidgets.QPushButton(self.frame_5)
        self.pb31.setGeometry(QtCore.QRect(110, 190, 80, 80))
        self.pb31.setMinimumSize(QtCore.QSize(80, 80))
        self.pb31.setMaximumSize(QtCore.QSize(80, 80))
        self.pb31.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb31.setText("")
        self.pb31.setObjectName("pb31")
        self.pb32 = QtWidgets.QPushButton(self.frame_5)
        self.pb32.setGeometry(QtCore.QRect(220, 190, 80, 80))
        self.pb32.setMinimumSize(QtCore.QSize(80, 80))
        self.pb32.setMaximumSize(QtCore.QSize(80, 80))
        self.pb32.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb32.setText("")
        self.pb32.setObjectName("pb32")
        self.pb33 = QtWidgets.QPushButton(self.frame_5)
        self.pb33.setGeometry(QtCore.QRect(330, 190, 80, 80))
        self.pb33.setMinimumSize(QtCore.QSize(80, 80))
        self.pb33.setMaximumSize(QtCore.QSize(80, 80))
        self.pb33.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb33.setText("")
        self.pb33.setObjectName("pb33")
        self.pb34 = QtWidgets.QPushButton(self.frame_5)
        self.pb34.setGeometry(QtCore.QRect(440, 190, 80, 80))
        self.pb34.setMinimumSize(QtCore.QSize(80, 80))
        self.pb34.setMaximumSize(QtCore.QSize(80, 80))
        self.pb34.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb34.setText("")
        self.pb34.setObjectName("pb34")
        self.pb35 = QtWidgets.QPushButton(self.frame_5)
        self.pb35.setGeometry(QtCore.QRect(550, 190, 80, 80))
        self.pb35.setMinimumSize(QtCore.QSize(80, 80))
        self.pb35.setMaximumSize(QtCore.QSize(80, 80))
        self.pb35.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb35.setText("")
        self.pb35.setObjectName("pb35")
        self.pb36 = QtWidgets.QPushButton(self.frame_5)
        self.pb36.setGeometry(QtCore.QRect(650, 190, 80, 80))
        self.pb36.setMinimumSize(QtCore.QSize(80, 80))
        self.pb36.setMaximumSize(QtCore.QSize(80, 80))
        self.pb36.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb36.setText("")
        self.pb36.setObjectName("pb36")
        self.pb20 = QtWidgets.QPushButton(self.frame_5)
        self.pb20.setGeometry(QtCore.QRect(10, 290, 80, 80))
        self.pb20.setMinimumSize(QtCore.QSize(80, 80))
        self.pb20.setMaximumSize(QtCore.QSize(80, 80))
        self.pb20.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb20.setText("")
        self.pb20.setObjectName("pb20")
        self.pb21 = QtWidgets.QPushButton(self.frame_5)
        self.pb21.setGeometry(QtCore.QRect(110, 290, 80, 80))
        self.pb21.setMinimumSize(QtCore.QSize(80, 80))
        self.pb21.setMaximumSize(QtCore.QSize(80, 80))
        self.pb21.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb21.setText("")
        self.pb21.setObjectName("pb21")
        self.pb22 = QtWidgets.QPushButton(self.frame_5)
        self.pb22.setGeometry(QtCore.QRect(220, 290, 80, 80))
        self.pb22.setMinimumSize(QtCore.QSize(80, 80))
        self.pb22.setMaximumSize(QtCore.QSize(80, 80))
        self.pb22.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb22.setText("")
        self.pb22.setObjectName("pb22")
        self.pb23 = QtWidgets.QPushButton(self.frame_5)
        self.pb23.setGeometry(QtCore.QRect(330, 290, 80, 80))
        self.pb23.setMinimumSize(QtCore.QSize(80, 80))
        self.pb23.setMaximumSize(QtCore.QSize(80, 80))
        self.pb23.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb23.setText("")
        self.pb23.setObjectName("pb23")
        self.pb24 = QtWidgets.QPushButton(self.frame_5)
        self.pb24.setGeometry(QtCore.QRect(440, 290, 80, 80))
        self.pb24.setMinimumSize(QtCore.QSize(80, 80))
        self.pb24.setMaximumSize(QtCore.QSize(80, 80))
        self.pb24.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb24.setText("")
        self.pb24.setObjectName("pb24")
        self.pb25 = QtWidgets.QPushButton(self.frame_5)
        self.pb25.setGeometry(QtCore.QRect(550, 290, 80, 80))
        self.pb25.setMinimumSize(QtCore.QSize(80, 80))
        self.pb25.setMaximumSize(QtCore.QSize(80, 80))
        self.pb25.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb25.setText("")
        self.pb25.setObjectName("pb25")
        self.pb26 = QtWidgets.QPushButton(self.frame_5)
        self.pb26.setGeometry(QtCore.QRect(650, 290, 80, 80))
        self.pb26.setMinimumSize(QtCore.QSize(80, 80))
        self.pb26.setMaximumSize(QtCore.QSize(80, 80))
        self.pb26.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb26.setText("")
        self.pb26.setObjectName("pb26")
        self.pb10 = QtWidgets.QPushButton(self.frame_5)
        self.pb10.setGeometry(QtCore.QRect(10, 390, 80, 80))
        self.pb10.setMinimumSize(QtCore.QSize(80, 80))
        self.pb10.setMaximumSize(QtCore.QSize(80, 80))
        self.pb10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb10.setText("")
        self.pb10.setObjectName("pb10")
        self.pb11 = QtWidgets.QPushButton(self.frame_5)
        self.pb11.setGeometry(QtCore.QRect(110, 390, 80, 80))
        self.pb11.setMinimumSize(QtCore.QSize(80, 80))
        self.pb11.setMaximumSize(QtCore.QSize(80, 80))
        self.pb11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb11.setText("")
        self.pb11.setObjectName("pb11")
        self.pb12 = QtWidgets.QPushButton(self.frame_5)
        self.pb12.setGeometry(QtCore.QRect(220, 390, 80, 80))
        self.pb12.setMinimumSize(QtCore.QSize(80, 80))
        self.pb12.setMaximumSize(QtCore.QSize(80, 80))
        self.pb12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb12.setText("")
        self.pb12.setObjectName("pb12")
        self.pb13 = QtWidgets.QPushButton(self.frame_5)
        self.pb13.setGeometry(QtCore.QRect(330, 390, 80, 80))
        self.pb13.setMinimumSize(QtCore.QSize(80, 80))
        self.pb13.setMaximumSize(QtCore.QSize(80, 80))
        self.pb13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb13.setText("")
        self.pb13.setObjectName("pb13")
        self.pb14 = QtWidgets.QPushButton(self.frame_5)
        self.pb14.setGeometry(QtCore.QRect(440, 390, 80, 80))
        self.pb14.setMinimumSize(QtCore.QSize(80, 80))
        self.pb14.setMaximumSize(QtCore.QSize(80, 80))
        self.pb14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb14.setText("")
        self.pb14.setObjectName("pb14")
        self.pb15 = QtWidgets.QPushButton(self.frame_5)
        self.pb15.setGeometry(QtCore.QRect(550, 390, 80, 80))
        self.pb15.setMinimumSize(QtCore.QSize(80, 80))
        self.pb15.setMaximumSize(QtCore.QSize(80, 80))
        self.pb15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb15.setText("")
        self.pb15.setObjectName("pb15")
        self.pb16 = QtWidgets.QPushButton(self.frame_5)
        self.pb16.setGeometry(QtCore.QRect(650, 390, 80, 80))
        self.pb16.setMinimumSize(QtCore.QSize(80, 80))
        self.pb16.setMaximumSize(QtCore.QSize(80, 80))
        self.pb16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb16.setText("")
        self.pb16.setObjectName("pb16")
        self.pb00 = QtWidgets.QPushButton(self.frame_5)
        self.pb00.setGeometry(QtCore.QRect(10, 490, 80, 80))
        self.pb00.setMinimumSize(QtCore.QSize(80, 80))
        self.pb00.setMaximumSize(QtCore.QSize(80, 80))
        self.pb00.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb00.setText("")
        self.pb00.setObjectName("pb00")
        self.pb01 = QtWidgets.QPushButton(self.frame_5)
        self.pb01.setGeometry(QtCore.QRect(110, 490, 80, 80))
        self.pb01.setMinimumSize(QtCore.QSize(80, 80))
        self.pb01.setMaximumSize(QtCore.QSize(80, 80))
        self.pb01.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb01.setText("")
        self.pb01.setObjectName("pb01")
        self.pb02 = QtWidgets.QPushButton(self.frame_5)
        self.pb02.setGeometry(QtCore.QRect(220, 490, 80, 80))
        self.pb02.setMinimumSize(QtCore.QSize(80, 80))
        self.pb02.setMaximumSize(QtCore.QSize(80, 80))
        self.pb02.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb02.setText("")
        self.pb02.setObjectName("pb02")
        self.pb03 = QtWidgets.QPushButton(self.frame_5)
        self.pb03.setGeometry(QtCore.QRect(330, 490, 80, 80))
        self.pb03.setMinimumSize(QtCore.QSize(80, 80))
        self.pb03.setMaximumSize(QtCore.QSize(80, 80))
        self.pb03.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb03.setText("")
        self.pb03.setObjectName("pb03")
        self.pb04 = QtWidgets.QPushButton(self.frame_5)
        self.pb04.setGeometry(QtCore.QRect(440, 490, 80, 80))
        self.pb04.setMinimumSize(QtCore.QSize(80, 80))
        self.pb04.setMaximumSize(QtCore.QSize(80, 80))
        self.pb04.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb04.setText("")
        self.pb04.setObjectName("pb04")
        self.pb05 = QtWidgets.QPushButton(self.frame_5)
        self.pb05.setGeometry(QtCore.QRect(550, 490, 80, 80))
        self.pb05.setMinimumSize(QtCore.QSize(80, 80))
        self.pb05.setMaximumSize(QtCore.QSize(80, 80))
        self.pb05.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb05.setText("")
        self.pb05.setObjectName("pb05")
        self.pb06 = QtWidgets.QPushButton(self.frame_5)
        self.pb06.setGeometry(QtCore.QRect(650, 490, 80, 80))
        self.pb06.setMinimumSize(QtCore.QSize(80, 80))
        self.pb06.setMaximumSize(QtCore.QSize(80, 80))
        self.pb06.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb06.setText("")
        self.pb06.setObjectName("pb06")
        self.gridLayout_3.addWidget(self.frame_5, 2, 0, 2, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.turnLabel = QtWidgets.QLabel(self.tab_4)
        self.turnLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.turnLabel.setFont(font)
        self.turnLabel.setStyleSheet("color:orange;")
        self.turnLabel.setText("")
        self.turnLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.turnLabel.setObjectName("turnLabel")
        self.gridLayout_6.addWidget(self.turnLabel, 0, 0, 1, 1)
        self.winLabel = QtWidgets.QLabel(self.tab_4)
        self.winLabel.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.winLabel.setFont(font)
        self.winLabel.setStyleSheet("color:purple;")
        self.winLabel.setText("")
        self.winLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.winLabel.setObjectName("winLabel")
        self.gridLayout_6.addWidget(self.winLabel, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_6, 0, 0, 1, 2)
        self.frame_6 = QtWidgets.QFrame(self.tab_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 600))
        self.frame_6.setMaximumSize(QtCore.QSize(200, 600))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.saveButton = QtWidgets.QPushButton(self.frame_6)
        self.saveButton.setGeometry(QtCore.QRect(50, 340, 100, 40))
        self.saveButton.setMinimumSize(QtCore.QSize(100, 30))
        self.saveButton.setMaximumSize(QtCore.QSize(100, 40))
        self.saveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveButton.setObjectName("saveButton")
        self.spinBox = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox.setGeometry(QtCore.QRect(150, 180, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(6, 180, 141, 20))
        self.label.setObjectName("label")
        self.playNowButton = QtWidgets.QPushButton(self.frame_6)
        self.playNowButton.setGeometry(QtCore.QRect(50, 250, 100, 40))
        self.playNowButton.setMinimumSize(QtCore.QSize(100, 30))
        self.playNowButton.setMaximumSize(QtCore.QSize(100, 40))
        self.playNowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playNowButton.setObjectName("playNowButton")
        self.playAgainButton = QtWidgets.QPushButton(self.frame_6)
        self.playAgainButton.setGeometry(QtCore.QRect(50, 420, 100, 40))
        self.playAgainButton.setMinimumSize(QtCore.QSize(100, 30))
        self.playAgainButton.setMaximumSize(QtCore.QSize(100, 40))
        self.playAgainButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playAgainButton.setObjectName("playAgainButton")
        self.gridLayout_3.addWidget(self.frame_6, 0, 2, 4, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.level_label.setText(_translate("MainWindow", "level"))
        self.levelComboBox.setItemText(0, _translate("MainWindow", "Easy"))
        self.levelComboBox.setItemText(1, _translate("MainWindow", "Medium"))
        self.levelComboBox.setItemText(2, _translate("MainWindow", "Hard"))
        self.startButton.setText(_translate("MainWindow", "start"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "Max waiting time is seconde"))
        self.playNowButton.setText(_translate("MainWindow", "Play Now"))
        self.playAgainButton.setText(_translate("MainWindow", "Play Again"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))

